# Project Name
TARGET = PitchBox

# Sources
CPP_SOURCES = \
	Source/PitchBox.cpp \
 	Source/FM/SinusoidSynth.cpp \
	Source/Ultrasonic/Ultrasonic.cpp

# Library Locations
LIBDAISY_DIR = Libraries/libDaisy
DAISYSP_DIR = Libraries/DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

